# -*- coding: utf-8 -*-
"""Assignment Schomee PY-C2-AS03_STRING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjR8B8es179ncjK0HfDw-LtLRBWFM9CK

## **STRING DATA TYPE**
# **CREATED BY SAMEER SIR**
# **AFTER COMPLETING KINDLY EMAIL TO msatutorpy@gmail.com**# 
**FOR EXAMPLE GIVING ASSIGNMENT FILENAME STARTING WITH YOUR NAME AS - SAMEER_PY_C2_AS04_LIST**
- **Questions based on String Data Type**
you can Subscribe my youtube channel for update helpful Tutorial videos https://www.youtube.com/channel/UCeQGGRl29zGZEwrZlUbszrQ
"""

# Explain What is STRING DATA TYPE with Properties & Example.

# # What is Output of below code or if Error then how to solve the Error ?
lang="     Python     "
print(lang)
print(lang.strip())

# # What is Output of below code or if Error then how to solve the Error ?
word=" Hello "
print(type(word))

# WAP to Remove blank space from lang variable.
lang="       Python      "

# WAP to Remove * symbol from left side only in lang variable.
lang="*******python******"

# WAP to Remove # symbol from right side only in lang variable.
lang="#######python######"

# WAP to Remove * symbol from right side only in lang variable.
lang="#######python******"

# WAP to Replace h to q and o to m in below variable using one single line of code.
lang="python"

#WAP to Replace p 2 times to space  in the whole string.
lang2="Python programming is popular in the Current world"

#WAP to Replace k to NaN  in the whole string.
lang2="Python programming is popular in the Current world"

#WAP to change # to _ in string.
lang3="Python is _ to the world."

#What is the Output of below code snippet, if any Error then how to solve that Error ?
lang="python c java"
print(lang.replace("t","S"))

# WAP to Change every characters case.
lang="Hello World" to hELLO wORLD

# WAP to Take string input from user and check whether string input all characters are in lowercase or not ?

# WAP to Take string input from user and check whether string input all characters are in uppercase or not?

# What is Output of below code or if Error then how to solve the Error ?
a="6666"
print(a.isnumeric())

# What is the difference between Capitalize()  & Title() string function with example?

# Explain and show the example of Center() & zfill() string function.

# Explain and show the example of ljust() & rjust() string function.

# What is Output of below code or if Error then how to solve the Error ?
name="python"
print(id(name))
print(hex(id(name)))

# What is Output of below code or if Error then how to solve the Error ?
print(type(boy))

# What is Output of below code or if Error then how to solve the Error ?
str1="a,b,c,d,e"
print(str1.split(","))

# What is Output of below code or if Error then how to solve the Error ?
str1="a","b","c"
print("_".join(str1))

# Explain and show the example of startswith() & endwith() string function.

# What is Output of below code or if Error then how to solve the Error ?
str2=" hi this is my python code".split()
print(str2)
print(type(str2))

# What is Output of below code or if Error then how to solve the Error ?
string="python is great"
print("max('python is great'):",max(string))
print("min('python is great'):",min(string))
str2="aa bb cc dd"
print("max('aa bb cc dd'):",max(str2))
print("min('aa bb cc dd'):",min(str2))
str3="aa","bb","cc","dd"
print(type(str3))
print('max("aa","bb","cc","dd):',max(str3))
print('min("aa","bb","cc","dd):',min(str3))
str4="aa","ab","ca","ac"
print('max("aa","ab","ca","ac"):',max(str4))
print('min("aa","ab","ca","ac"):',min(str4))

# What is Output of below code or if Error then how to solve the Error ?
string2="This is the World of my PYthon programming."
print(string2.swapcase())
print(string2.capitalize())
print(string2.title())
print(string2.islower())
string3="1234578692104"
print(string3.isdigit())
print(string3.isnumeric())
string4="hI1333"
print(string4.isnumeric())
print(string4.isdigit())
print(type(string4.isdigit()))
print(len(string4))

# What is Output of below code or if Error then how to solve the Error ?
string5="This Is The World of Python Programming"
print(string5.istitle())
string="Python Is Great"
string.istitle()

# What is Output of below code or if Error then how to solve the Error ?
string5="This Is The World of Python Programming"

print(string5.iscapitalize())

# What is Output of below code or if Error then how to solve the Error ?
name=" Hello              World   "
print(name.isspace())
str1="      "
print(str1.isspace())

# What is Output of below code or if Error then how to solve the Error ?
string5="This Is The World of Python Programming"
print(string5.count('P'))
print(string5.count("p"))
print(string5.count("K"))

# What is Output of below code or if Error then how to solve the Error ?
string5="This Is The World of Python Programming"
print("The" in string5)
print("the" in string5)
print("MY" in string5)
print("My" not in string5)
print(type("My" not in string5))

# What is Output of below code or if Error then how to solve the Error ?
str1="aa"
str2="bb"
print(str1<str2)
print(str1>str2)
print(id(str1))
print(id(str2))
print(str1==str2)
str4="aa"
print(str4==str1)

#What are different between index string method and find string method,Explain with example?

#What is the Output of below code snippet, if any Error then how to solve that Error ?
lang="Python"
print(isinstance(lang,str))

##What is the Output of below code snippet, if any Error then how to solve that Error ?
num=10
print(isinstance(num,int))

##What is the Output of below code snippet, if any Error then how to solve that Error ?
num=10
print(isinstance(num,str))

# Write the detail what isinstance() function do with example.

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.find("w"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.index("w"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.rfind("i"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.lfind("i"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.rindex("i"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="This world is having lots of Programming Languages"
print(str1.lindex("i"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
s="this is python"
print(s.startswith("this"))
print(s.startswith("h",1,5))
print(s.startswith("hi",1,5))
print(s.startswith("hiss",1,5))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
s="this is python"
pfind=s.find("p")
print(pfind)
print(s.startswith("p",pfind,15))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
symbol="#"
str1="aa","bb","cc"
print(symbol.join(str1))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
str1="aa#bb#cc"
print(str1.split("#"))

# Is there any different between Join String method and Split String method , Explain with Example?

#WAP to print the output as ['hamza', 'aar', 'gmail', 'com'] using string method only.

eid="hamza.aar@gmail.com"
#output should come as ['hamza', 'aar', 'gmail', 'com']

#What is the Output of below code snippet, if any Error then how to solve that Error ?

str1="Hello "
str2="Python"
str4="programming"
print("str1.lower():",str1.lower())
print("str4.islower(): ",str4.islower())

str3=(str1[0].lower())
print("str3:",str3)
print("str1[1].islower():",str1[1].islower())

#What is the Output of below code snippet, if any Error then how to solve that Error ?

print(max("aa bb cc dd"))

print(max("aa""bb""cc""dd"))

print(max("aa","bb","cc","dd"))

print(max("aa","ab","bc","db","da"))