# -*- coding: utf-8 -*-
"""PY-C2-AS04_LIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZ2magL8tROwqZI0IjmaAjqxFHVxrTCn

## **LIST ASSIGNMENT** ##
# **CREATED BY SAMEER_SAKIB SIR**
# **AFTER COMPLETING ASSIGNMENT WITH YOURFILE NAME KINDLY EMAIL TO msatutorpy@gmail.com**
# **FOR EXAMPLE GIVING ASSIGNMENT FILENAME STARTING WITH YOUR NAME AS - SAMEER_PY_C2_AS04_LIST**



# **you can join the facebook group for day to day update https://www.facebook.com/groups/681374459356106/** 


# **you can Subscribe my youtube channel for update helpful Tutorial videos  https://www.youtube.com/channel/UCeQGGRl29zGZEwrZlUbszrQ**
"""

# Explain What is LIST DATA TYPE with Properties & Example..

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[11,33,33,44]
print(type(list1))
print(list1)

# Write code in python  to show an example of list data type having heterogenous property.

#Write code in python to show if list1=[11,33,55,77] , how you can make list1 = [11,22,33,55,77,99] by using list function.

#Write code in python to show if list2=[hi,1,3,3,4,5] then how you can make list2=[hi,1,3,3,5] using list function.

#Write code in python to show. 
# if list1=[11,22]
# if list2=[33,44]
then make a new list3 contain the values of list1 & list2 .

#Write code in python to show. 
# if list4=["10",3,5,True]
then by using list function make list4 empty list.

#Write code in python to 
# show the example of min and max properties of list data type.

#What is the Output of below code snippet, if any Error then how to solve that Error ?

list5=[77,88,10,True,78,23,32,90]
print("Before pop elements number:",len(list5))
print("list5.index(10):",list5.index(10))
print("list5.pop(3):",list5.pop(3))
print("After pop elements number:",len(list5))

#What is the Output of below code snippet, if any Error then how to solve that Error ?

list5=[77,88,True,78,23,32,90]
print("list5.pop():",list5.pop())
print("After pop elements number:",len(list5))

#What is different between REMOVE() function & POP() function, Explain with Example.

#Answer -
'''
IN remove() we provide the exact element value 
whereas in pop() we provide the index number of element which element we want to delete.'''
list1=[10,11,12,13]
print("remove:",list1.remove(11))
print("pop:",list1.pop(2))
print("list:",list1)

#What is different between INDEX() function & POP() function, Explain with Example.

#Write code in python to show . 
list6=[77,88,99,34,11,2]
#then sort the list6 using list method.

list6.sort()
print("list:",list6)

#Write code in python
#if list6=[77,88,99,34,11,2] 
#then make list6=[99,88,77,34,11,2] using list method.

list6=[77,88,99,34,11,2] 
indexnumberof77=list6.index(77)
print(indexnumberof77)
list6[indexnumberof77]=99
list6[list6.index(99)]=77
print("list:",list6)

# # What is Output of below code or if Error then how to solve the Error ?
print(min(list6))
print(max(list6))

# #Write code in python to find the sum of all the  elements of list6 elements using list method.

print(sum(list6))

print(dir(list))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
print(add(list6))

#Hint- no add function

#What is the Output of below code snippet, if any Error then how to solve that Error ?
print(mul(list6))

#Hint- no mul function

# #Write code in python.
# if list7=[1,2,3,4,5,1]
find the index number of second 1 element using list method.

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3,[4,5]]
l1[3][0]='a'
print(l1)
print(l1[3])
print(l1[2])

#What is the Output of below code snippet, if any Error then how to solve that Error ?
c1=[1,2,3]
c2=[4,5,6]
c1.append(c2)
print(c1)

print(len(c1))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
c1=[1,2,3]
c2=[4,5,6]
c1.append(-2,"Hello") # Hint- trying to give index number and value in append function
print(c1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
c1=[1,2,3]
c2=[4,5,6]
c1.extend(c2)
print(c1)
print(len(c1))

#What is the difference you are able to findout in above code example?
#How using append is differ than using extend?

#How using append is differ than using extend?

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a1=[10,11,12]
b1=[20,21]
a1.append(b1)
print(a1)
a1.extend(b1)
print(a1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list2=[11,33]
del list2
print(list2)

#Write code in python to show different between remove() & pop() function of list data type.

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[11,44,889,7]
list1.remove(7)
print(list1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[11,44,889,7]
list1.pop(2)
print(list1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[11,44,889,7]

list1.pop(50)
print(list1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[11,44,889,7]

list1.pop()
print(list1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a2=[2,4,6,8,0,7,5,3,1]
a2.sort()
print (a2)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a2=[2,4,6,8,0,7,5,3,1]
a2.sort(reverse=True)
print (a2)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a2=[12,14,6,18,0,17]
a2.reverse()
print (a2)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a1=[2,4,6,8,0,7,5,3,1]
a1.sort()
print(a1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
b1=[12,14,16,18,0,17]
a2=sorted(a1)
print(a1)

#What is the difference you are able to findout in above code example?
#How using sorted() is differ than using sort()?

Hint:- Original list changing.

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a1=[2,4,6,8,0,7,5,3,1]
a2=sorted(a1,reverse=True)
print(a2)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a1=[1,3,5,2,4,6]
a2=reversed(a1) 
print (a2)
print (list(a2))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a1=[1,2,3,4,5,6,7,8,9,10]
print (min(a1)) 
print (max(a1))
print (sum(a1))
print (len(a1))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3,4,5]
l2=l1.copy()
print("l2:",l2)
print("l1:",l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3,4,5]
l2=l1.copy()
l1[0]="list1newvalue"
print("l2:",l2)
print("l1:",l1)

#Hints:Copy of list variable

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3,4,5]
l2=l1
l1[0]="list1newvalue"
print("l2:",l2)
print("l1:",l1)

#Hint:Assignment operator =

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l2=[100,101,102,103,104,105,106]
print(l2[-0])

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l2=[100,101,102,103,104,105,106]
print(l2[-1])

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l2=[100,101,102,103,104,105,106]
print(l2[-2])

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l2=[100,101,102,103,104,105,106]
print(l2[-200])

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(3,899)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?1
l1=[11,22,33,44,55]
l1.insert(3,899)# In this insert function what is 3 and what is 899 ?

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(-0,8899)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(-1,99)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(-1,299)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(2000,899)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,22,33,44,55]
l1.insert(899)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l3=[11,22,33,44]
print(l3.index(33))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l3=[11,22,33,44]
print(l3.index("33"))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l3=[11,22,33,44]
print(l3.find(33))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3,4,5]
l2=l1
l1[0]="list1newvalue"
print("l2:",l2)
print("l1:",l1)

print('l2:', ['list1newvalue', 2, 3, 4, 5])
print('l1:', ['list1newvalue', 2, 3, 4, 5])

#What is the Output of below code snippet, if any Error then how to solve that Error ?

l1=[1,2,3,4,5]
l2=l1.copy()
l1[0]="list1newvalue"
print("l2:",l2)
print("l1:",l1)

print('l2:', ['list1newvalue', 2, 3, 4, 5])
print('l1:', ['list1newvalue', 2, 3, 4, 5])

#What is the Output of below code snippet, if any Error then how to solve that Error ?

list7=[1,2,3,4,5,1,0,0,7,7,9,9,88,1,1,1]

print(list7.index(1,-1))

#What is the difference between append function and extend function of list data type?
#show the difference with example.

#What is the Output of below code snippet, if any Error then how to solve that Error ?

'''
list method which will update the original list are:
 append,extend,remove,clear,pop,insert,sort,reverse

list function which will return new list and won’t modify the original list are:
 sorted() , reversed(),copy()
 '''

#What is the Output of below code snippet, if any Error then how to solve that Error ?
list1=[10,11,12]
print(id(list1))
print(id(list1[0]))
print(id(list1[1]))
print(id(list1[2]))

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,2,3,44,5]
l1.sort()
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,2,3,44,5]
l1.sort(reverse=True)
print(l1)

l1=[11,2,3,44,5]
sorted(l1)
print(sorted(l1))
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[11,2,3,44,5]
l1=sorted(l1)
print(sorted(l1))
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
c1=[1,2,3]
c2=[4,5,6]
c1.append("Hello")
c1.append(-2)
print(c1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
l1=[1,2,3]
l2=[11,22,33]
l1.extend(l2)
print(l1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?

l2=[11,34,"bye",78.999]

l1=[22,33,66,77]

print(l1*l2)

#What is the Output of below code snippet, if any Error then how to solve that Error ?

l2=[11,34,"bye",78.999]

l1=[22,33,66,77]

print(l2*3)

#What is the Output of below code snippet, if any Error then how to solve that Error ?

l3=[7*8*9]  
print(l3)

