# -*- coding: utf-8 -*-
"""PY_C2_AS09_QNS_FLOW_CONTROL_PART1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDk28M_5qV8bae0MhyeneOTpGi65XuQi

## **FLOWCONTROL_PART1 ASSIGNMENT** ##
# **CREATED BY SAMEER SIR**
# **AFTER COMPLETING ASSIGNMENT KINDLY EMAIL TO **
# **FOR EXAMPLE GIVING ASSIGNMENT FILENAME STARTING WITH YOUR NAME AS - SAMEER_PY_C2_AS04_LIST**
"""

print("Hello World")

# WHAT DO YOU MEAN BY FLOW CONTROL IN PYTHON PROGRAMMING?

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a=10
if a==10:
  print("Number is :",a)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
name=input("Enter your name:")

if name=='Python':
  print("Hello Python.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
name=input("Enter your name:")
print(type(name))
if type("sameer")==("<class 'str'>"):
  print("hello")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
name=input("Enter your name:")
if isinstance(name,str):
  print("Hello",name)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
if num1==10:
  print("Number 1 is:"num1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
if num1==10:
  print("Number 1 is:",num1)

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=20
if num2!=20:
  print("Number 2 is not 20")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=20
if num2!=20:
  print("Number 2 is not 20.")
else:
  print("Number 2 is 20.")

num1=10
num2=20
if num2!=20:
  print("Number 2 is not 20.")
elif num2==20:
  print("Number 2 is 20.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=20
if num2!=20:
  print("Number 2 is not 20.")
elif num2==20:
  print("Number 2 is 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num2!=20:
  print("Number 2 is not 20.")
elif num2==20:
  print("Number 2 is 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=40
if num2!=20:
  print("Number 2 is not 20.")
elif num2==20:
  print("Number 2 is 20.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num2!=20:
  print("Number 2 is not 20.")
else:
  print("Thank you.")
elif num2==20:
  print("Number 2 is 20.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num2!=20:
  print("Number 2 is not 20.")
else:
  print("Thank you.")
elif num2==20:
  print("Number 2 is 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==30:
    print("Number 2 is 30.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  else:
    print("Number 2 is not 20")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=30
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=40
if num1==40:#flow control 1
  print("Number 2 is not 20.")

elif num1==10:#flow control 1
  print("Number 1 is 10.")
  if num2==20:#flow control 2
    print("Number 2 is 20.")
  elif num2==30:#flow control 2
    print("Number 2 is 30")
  else:#flow control 2
    print("Number 2 is not 30 nor 20.")
else:#flow control 1
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=40
num2=40
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=40
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=40
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  else:
    print("Number 2 is not 30 nor 20.")
  elif num2==30:
    print("Number 2 is 30")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=10
num2=40
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  else:
    print("Number 2 is not 30 nor 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50:
    print("Number1 is 50.")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=60
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1=50:
    print("Number1 is 50.")
  else:
    print("Number1 is not 50.")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=60
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1=50:
    print("Number1 is 50.")
  elif num2==50:
    print("Number 2 is 50")
  else:
    print("Number1 is not 50.")
  print("Thank you.")



#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=60
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1=50:
    print("Number1 is 50.")
  elif num2==50:
    print("Number 2 is 50")
  else:
    print("Number1 is not 50.")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50:
    print("Number1 is 50.")
  elif num2==50:
    print("Number 2 is 50")
  else:
    print("Number1 is not 50.")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50:
    print("Number1 is 50.")
  else:
    print("Number1 is not 50.")
  elif num2==50:
    print("Number 2 is 50")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")

  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50:
    print("Number1 is 50.")
  elif num2==50:
    print("Number 2 is 50")
    print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")

  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50:
    print("Number1 is 50.")
  elif num2==70:
    print("Number 2 is 50")
  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=50
num2=50
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==10:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50 and num2==50 and num3==50:
    print("All numbers are 50.")

  print("Thank you.")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num1=40
num2=40
num3=50
if num1==40:
  print("Number 2 is not 20.")

elif num1==40:
  print("Number 1 is 10.")
  if num2==20:
    print("Number 2 is 20.")
  elif num2==30:
    print("Number 2 is 30")
  else:
    print("Number 2 is not 30 nor 20.")
else:
  if num1==50 and num2==50 and num3==50:
    print("All numbers are 50.")

  print("Thank you.")

#Write a python programme which take number from user and check whether the number entered is even or odd.

#Write a python programme which check year entered by user is leap year or not ?

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a=30
if a==10:
  print("inside if.")
  print("inside if line2")

if a==30:
  print("inside second if ")
  print("a value inside second if is:",a)
  
if a==30:
  print("inside second if ")
  print("a value inside second if is:",a)

elif a==20:
  print("inside elif")
  print("a value is :",a)

else:
  print("inside else")
  print("a value is: neither 20 nor 10")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
a=30
if a==10:
  print("inside if.")
  print("inside if line2")


elif a==20:
  print("inside elif")
  print("a value is :",a)


if a==30:
  print("inside second if ")
  print("a value inside second if is:",a)

else:
  print("inside else")
  print("a value is: neither 20 nor 10")

#What is the Output of below code snippet, if any Error then how to solve that Error ?
num=30
num2=25
if num<20:
  print("number is less than 20")
if num==10:
  print("number is 10")

elif num==40:
  if num2==25:
    print("Number2 is 20")
  else:
    print("Number2 is not 20")
  elif num2==5:
    print("number2 is 25")

  print("Number1 is 30")
  
else:
  print("number is  not 10")

b=20
if b<30:
    print("Bismoy")

if b<25:
    print("Chandni")

if b<15:
    print("Mohammad")
    

elif b<40:
    print("Dayuf")
    
if b<35:
    print("python")
else:
    print("Boaring sameer")

b=20

if b<30:
    print("Bismoy")

if b<25:
    print("Chandni")

else:
    print("Boaring sameer")

if b<15:
    print("Mohammad")

elif b<40:
    print("Dayuf")

else:
    print("Boaring sameer")

b=20
if b<30:
    print("Bismoy")

if b<25:
    print("Chandni")

elif b<45: #else if
    print("Mohammad")
    

elif b<40:
    print("Dayuf")
    
if b<35:
    print("python")
else:
    print("Boaring sameer")

b=20

elif b<45: #else if
    print("Mohammad")
  
if b<30:
    print("Bismoy")

elif b<45: #else if
    print("Mohammad")  

elif b<40:
    print("Dayuf")
    
if b<35:
    print("python")
else:
    print("Boaring sameer")